name: Replace
on:  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: SummerSec/gha-find-replace@master
        with:
          find: "SummerSec/template"
          replace: ${{ github.repository }}
          regex: false
          include: "README.md" # 需要替换的文件内容
      - name: Push changes
        uses: SummerSec/push@master # 更新README.md
        with:
          github_token: ${{ secrets.RELEASE }} # github token